#!/bin/bash
  # ls -l:以长格式列出文件的详细信息
  # 每行前 10 个字符的含义:
  #   第 1 位  = 文件类型(- 普通文件 / d 目录 / l 符号链接 / c 字符设备 / b 块设备)
  #   第 2-4 位  = 属主(owner)权限: r 读 / w 写 / x 执行 / - 无
  #   第 5-7 位  = 属组(group)权限: 同上
  #   第 8-10 位 = 其他人(others)权限: 同上
  #   特殊位:s = setuid/setgid,t = 粘滞位(例如 /tmp 的 drwxrwxrwt)
  ls -l /

